# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: market_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'market_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11market_data.proto\x12\nmarketdata\"`\n\x04Tick\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x0e\n\x06volume\x18\x03 \x01(\x01\x12\x16\n\x0eis_buyer_maker\x18\x04 \x01(\x08\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"\x91\x01\n\x06Signal\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\tdirection\x18\x02 \x01(\t\x12\x13\n\x0b\x65ntry_price\x18\x03 \x01(\x01\x12\x13\n\x0b\x65xpected_sl\x18\x04 \x01(\x01\x12\x13\n\x0b\x65xpected_tp\x18\x05 \x01(\x01\x12\x12\n\nconfidence\x18\x06 \x01(\x01\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\"8\n\x0cTickResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x17\n\x0fticks_processed\x18\x02 \x01(\x05\"\x1f\n\rSignalRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t2\x96\x01\n\x11MarketDataGateway\x12=\n\x0bStreamTicks\x12\x10.marketdata.Tick\x1a\x18.marketdata.TickResponse\"\x00(\x01\x12\x42\n\rStreamSignals\x12\x19.marketdata.SignalRequest\x1a\x12.marketdata.Signal\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TICK']._serialized_start=33
  _globals['_TICK']._serialized_end=129
  _globals['_SIGNAL']._serialized_start=132
  _globals['_SIGNAL']._serialized_end=277
  _globals['_TICKRESPONSE']._serialized_start=279
  _globals['_TICKRESPONSE']._serialized_end=335
  _globals['_SIGNALREQUEST']._serialized_start=337
  _globals['_SIGNALREQUEST']._serialized_end=368
  _globals['_MARKETDATAGATEWAY']._serialized_start=371
  _globals['_MARKETDATAGATEWAY']._serialized_end=521
# @@protoc_insertion_point(module_scope)
